# stable-diffusion-v1-5
[[sources]]
repo = "botp/stable-diffusion-v1-5"
files = ["v1-5-pruned-emaonly.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "botp/stable-diffusion-v1-5"
files = [
    "model_index.json",
    "feature_extractor/preprocessor_config.json",
    "safety_checker/config.json",
    "scheduler/scheduler_config.json",
    "text_encoder/config.json",
    "tokenizer/merges.txt",
    "tokenizer/special_tokens_map.json",
    "tokenizer/tokenizer_config.json",
    "tokenizer/vocab.json",
    "unet/config.json",
    "vae/config.json",
]
path = "models/configs/stable-diffusion-v1-5"

# stable-diffusion-2-inpainting
[[sources]]
repo = "stabilityai/stable-diffusion-2-inpainting"
files = ["512-inpainting-ema.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "stabilityai/stable-diffusion-2-inpainting"
files = [
    "model_index.json",
    "feature_extractor/preprocessor_config.json",
    "scheduler/scheduler_config.json",
    "text_encoder/config.json",
    "tokenizer/merges.txt",
    "tokenizer/special_tokens_map.json",
    "tokenizer/tokenizer_config.json",
    "tokenizer/vocab.json",
    "unet/config.json",
    "vae/config.json",
]
path = "models/configs/stable-diffusion-2-inpainting"

# stable-diffusion-2-1
[[sources]]
repo = "stabilityai/stable-diffusion-2-1"
files = ["v2-1_768-ema-pruned.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "stabilityai/stable-diffusion-2-1"
files = [
    "model_index.json",
    "feature_extractor/preprocessor_config.json",
    "scheduler/scheduler_config.json",
    "text_encoder/config.json",
    "tokenizer/merges.txt",
    "tokenizer/special_tokens_map.json",
    "tokenizer/tokenizer_config.json",
    "tokenizer/vocab.json",
    "unet/config.json",
    "vae/config.json",
]
path = "models/configs/stable-diffusion-2-1"

# stable-diffusion-xl-base-1.0
[[sources]]
repo = "stabilityai/stable-diffusion-xl-base-1.0"
files = ["sd_xl_base_1.0.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "stabilityai/stable-diffusion-xl-base-1.0"
files = [
    "model_index.json",
    "scheduler/scheduler_config.json",
    "text_encoder/config.json",
    "text_encoder_2/config.json",
    "tokenizer/merges.txt",
    "tokenizer/special_tokens_map.json",
    "tokenizer/tokenizer_config.json",
    "tokenizer/vocab.json",
    "tokenizer_2/merges.txt",
    "tokenizer_2/special_tokens_map.json",
    "tokenizer_2/tokenizer_config.json",
    "tokenizer_2/vocab.json",
    "unet/config.json",
    "vae/config.json",
    "vae_1_0/config.json",
    "vae_decoder/config.json",
    "vae_encoder/config.json",
]
path = "models/configs/stable-diffusion-xl-base-1.0"

# stable-diffusion-xl-refiner-1.0
[[sources]]
repo = "stabilityai/stable-diffusion-xl-refiner-1.0"
files = ["sd_xl_refiner_1.0.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "stabilityai/stable-diffusion-xl-refiner-1.0"
files = [
    "model_index.json",
    "scheduler/scheduler_config.json",
    "text_encoder_2/config.json",
    "tokenizer_2/merges.txt",
    "tokenizer_2/special_tokens_map.json",
    "tokenizer_2/tokenizer_config.json",
    "tokenizer_2/vocab.json",
    "unet/config.json",
    "vae/config.json",
    "vae_1_0/config.json",
]
path = "models/configs/stable-diffusion-xl-refiner-1.0"

# stable-diffusion-3-medium-diffusers
[[sources]]
repo = "ckpt/stable-diffusion-3-medium"
files = [
    { src = "sd3_medium_incl_clips_t5xxlfp8.safetensors", dest = "checkpoints/sd3_medium_incl_clips_t5xxlfp8.safetensors" },
    { src = "text_encoders/t5xxl_fp16.safetensors", dest = [
        "clip/t5xxl_fp16.safetensors",
    ] },
]
path = "models"

[[sources]]
repo = "Infinirc/stable-diffusion-3-medium-diffusers"
files = [
    { src = "text_encoder/model.fp16.safetensors", dest = [
        "clip/clip_l.safetensors",
        "configs/stable-diffusion-3-medium-diffusers/text_encoder/model.fp16.safetensors",
    ] },
    { src = "text_encoder_2/model.fp16.safetensors", dest = [
        "clip/clip_g.safetensors",
        "configs/stable-diffusion-3-medium-diffusers/text_encoder_2/model.fp16.safetensors",
    ] },
    { src = "text_encoder_3/model.fp16-00001-of-00002.safetensors", dest = [
        "configs/stable-diffusion-3-medium-diffusers/text_encoder_3/model.fp16-00001-of-00002.safetensors",
    ] },
    { src = "text_encoder_3/model.fp16-00002-of-00002.safetensors", dest = [
        "configs/stable-diffusion-3-medium-diffusers/text_encoder_3/model.fp16-00002-of-00002.safetensors",
    ] },
]
path = "models"

[[sources]]
repo = "Infinirc/stable-diffusion-3-medium-diffusers"
files = [
    "model_index.json",
    "scheduler/scheduler_config.json",
    "text_encoder/config.json",
    "text_encoder_2/config.json",
    "text_encoder_3/config.json",
    "text_encoder_3/model.safetensors.index.fp16.json",
    "tokenizer/merges.txt",
    "tokenizer/special_tokens_map.json",
    "tokenizer/tokenizer_config.json",
    "tokenizer/vocab.json",
    "tokenizer_2/merges.txt",
    "tokenizer_2/special_tokens_map.json",
    "tokenizer_2/tokenizer_config.json",
    "tokenizer_2/vocab.json",
    "tokenizer_3/special_tokens_map.json",
    "tokenizer_3/spiece.model",
    "tokenizer_3/tokenizer.json",
    "tokenizer_3/tokenizer_config.json",
    "transformer/config.json",
    "vae/config.json",
]
path = "models/configs/stable-diffusion-3-medium-diffusers"

# anything-v3.0
[[sources]]
repo = "ckpt/anything-v3.0"
files = ["Anything-V3.0.ckpt"]
path = "models/checkpoints"

# kolors
[[sources]]
repo = "Kijai/ChatGLM3-safetensors"
files = [
    { src = "chatglm3-fp16.safetensors", dest = [
        "LLM/chatglm3-fp16.safetensors",
        "configs/Kolors-diffusers/text_encoder/model.fp16.safetensors",
    ] },
]
path = "models"

[[sources]]
repo = "Kwai-Kolors/Kolors"
files = [
    { src = "unet/diffusion_pytorch_model.fp16.safetensors", dest = [
        "unet/diffusion_pytorch_model.fp16.safetensors",
        "unet/kolors-unet.safetensors",
        "configs/Kolors-diffusers/unet/diffusion_pytorch_model.fp16.safetensors",
    ] },
    { src = "vae/diffusion_pytorch_model.fp16.safetensors", dest = [
        "vae/diffusion_pytorch_model.fp16.safetensors",
        "vae/kolors.vae.safetensors",
        "vae/sdxl.vae.safetensors",
        "configs/Kolors-diffusers/vae/diffusion_pytorch_model.fp16.safetensors",
        "configs/stable-diffusion-v1-5/vae/diffusion_pytorch_model.fp16.safetensors",
    ] },
]
path = "models"

[[sources]]
repo = "Kwai-Kolors/Kolors"
files = [
    "model_index.json",
    "scheduler/scheduler_config.json",
    "text_encoder/config.json",
    "tokenizer/tokenizer_config.json",
    "tokenizer/tokenizer.model",
    "tokenizer/vocab.txt",
    "unet/config.json",
    "vae/config.json",
]
path = "models/configs/Kolors-diffusers"

# other checkpoints
[[sources]]
repo = "WarriorMama777/OrangeMixs"
files = [
    { src = "Models/AbyssOrangeMix2/AbyssOrangeMix2_hard.safetensors", dest = "AbyssOrangeMix2_hard.safetensors" },
    { src = "Models/AbyssOrangeMix3/AOM3A3_orangemixs.safetensors", dest = "AOM3A3.safetensors" },
    { src = "Models/AbyssOrangeMix3/AOM3A1_orangemixs.safetensors", dest = "AOM3A1.safetensors" },
]
path = "models/checkpoints"


[[sources]]
repo = "jomcs/NeverEnding_Dream-Feb19-2023"
files = [
    { src = "CarDos%20Anime/cardosAnime_v10.safetensors", dest = "cardosAnime_v10.safetensors" },
]
path = "models/checkpoints"

# controlnet
[[sources]]
repo = "comfyanonymous/ControlNet-v1-1_fp16_safetensors"
files = [
    { src = "control_v11p_sd15_scribble_fp16.safetensors", dest = [
        "control_v11p_sd15_scribble_fp16.safetensors",
        "control_scribble.safetensors",
    ] },
    { src = "control_v11p_sd15_openpose_fp16.safetensors", dest = [
        "control_v11p_sd15_openpose_fp16.safetensors",
        "control_openpose.safetensors",
    ] },
    { src = "control_v11f1p_sd15_depth_fp16.safetensors", dest = [
        "control_v11f1p_sd15_depth_fp16.safetensors",
        "control_depth.safetensors",
    ] },
]
path = "models/controlnet"

[[sources]]
repo = "lllyasviel/control_v11p_sd15_canny"
files = ["config.json"]
path = "models/configs/control_v11p_sd15_canny"


[[sources]]
repo = "InstantX/SD3-Controlnet-Canny"
files = [
    { src = "diffusion_pytorch_model.safetensors", dest = [
        "configs/SD3-Controlnet-Canny/diffusion_pytorch_model.safetensors",
        "controlnet/sd3_controlnet_canny.safetensors",
    ] },
    { src = "config.json", dest = "configs/SD3-Controlnet-Canny/config.json" },
]
path = "models"

# vae
[[sources]]
repo = "stabilityai/sd-vae-ft-mse-original"
files = ["vae-ft-mse-840000-ema-pruned.safetensors"]
path = "models/vae"

[[sources]]
url = "https://hf-mirror.com/hakurei/waifu-diffusion-v1-4/resolve/5c5d89ee15d82f346fe10290da173abcd6d89c0a/"
files = ["vae/kl-f8-anime2.safetensors"]
path = "models"


# custom_nodes
[[sources]]
url = "https://github.com/MinusZoneAI/"
files = [{ src = "ComfyUI-Kolors-MZ.git", dest = "ComfyUI-Kolors-MZ" }]
path = "custom_nodes"

[[sources]]
url = "https://github.com/ltdrdata/"
files = [{ src = "ComfyUI-Manager.git", dest = "ComfyUI-Manager" }]
path = "custom_nodes"

[[sources]]
url = "https://github.com/Gourieff/"
files = [{ src = "comfyui-reactor-node.git", dest = "comfyui-reactor-node" }]
path = "custom_nodes"

# loras
[[sources]]
repo = "stabilityai/stable-diffusion-xl-base-1.0"
files = ["sd_xl_offset_example-lora_1.0.safetensors"]
path = "models/loras"

[[sources]]
url = "https://hf-mirror.com/mirroring/civitai_mirror/resolve/f500ffe47d2208d680de784154b30984ad6a4ffe/models/Lora/"
files = [
    "theovercomer8sContrastFix_sd15.safetensors",
    "epiNoiseoffset_v2.safetensors",
]
path = "models/loras"

# safety_checker
[[sources]]
repo = "CompVis/stable-diffusion-safety-checker"
files = ["config.json", "pytorch_model.bin", "preprocessor_config.json"]
path = "models/configs/stable-diffusion-safety-checker"


# for benchmark
[[sources]]
repo = "liamhvn/epiCPhotoGasm-ultimate-fidelity"
files = [
    { src = "epicphotogasm_ultimateFidelity.safetensors", dest = "epicphotogasm_x.safetensors" },
]
path = "models/checkpoints"

[[sources]]
repo = "Justin-Choo/epiCRealism-Natural_Sin_RC1_VAE"
files = ["epicrealism_naturalSinRC1VAE.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "Bingsu/adetailer"
files = ["face_yolov8m.pt", "hand_yolov8s.pt", "face_yolov8n_v2.pt"]
path = "models/ultralytics/bbox"

[[sources]]
repo = "GRBalance8/Eyeful_v2-paired"
files = ["Eyeful_v2-Paired.pt"]
path = "models/ultralytics/bbox"

[[sources]]
repo = "datasets/mpiquero/Upscalers"
files = ["x1_ITF_SkinDiffDetail_Lite_v1.pth"]
path = "models/upscale_models"

[[sources]]
repo = "gemasai/4x_NMKD-Siax_200k"
files = ["4x_NMKD-Siax_200k.pth"]
path = "models/upscale_models"

[[sources]]
repo = "Phips/4xFaceUpDAT"
files = ["4xFaceUpDAT.safetensors"]
path = "models/upscale_models"

[[sources]]
repo = "zzed/epiCRealismHelper-V1_Lora"
files = ["epiCRealismHelper.safetensors"]
path = "models/loras"


[[sources]]
repo = "frankjoshua/more_details"
files = ["more_details.safetensors"]
path = "models/loras"


[[sources]]
repo = "Vhey/action-sdxl"
files = ["action-sdxl-V0.5.safetensors"]
path = "models/loras"

[[sources]]
repo = "Kijai/SUPIR_pruned"
files = ["SUPIR-v0F_fp16.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "RunDiffusion/Juggernaut-XL-v8"
files = ["juggernautXL_v8Rundiffusion.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "kaliansh/sdrep"
files = ["GFPGANv1.3.pth"]
path = "models/facerestore_models"

[[sources]]
url = "https://hf-mirror.com/luca115/stable-diffusion/blob/09f157d8faf92a7e8c327f1c83ea108dc20acfe0/facerestore_models/"
files = ["codeformer.pth"]
path = "models/facerestore_models"


[[sources]]
repo = "digiplay/majicMIX_realistic_v7"
files = ["majicmixRealistic_v7.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "ezioruan/inswapper_128.onnx"
files = ["inswapper_128.onnx"]
path = "models/onnx"


[[sources]]
repo = "TheMistoAI/MistoLine"
files = ["mistoLine_fp16.safetensors", "mistoLine_rank256.safetensors"]
path = "models/controlnet"


[[sources]]
repo = "Comfy-Org/flux1-dev"
files = ["flux1-dev-fp8.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "Comfy-Org/flux1-schnell"
files = ["flux1-schnell-fp8.safetensors"]
path = "models/checkpoints"

[[sources]]
repo = "InstantX/FLUX.1-dev-Controlnet-Canny"
files = [
    { src = "diffusion_pytorch_model.safetensors", dest = "instantx_flux_canny.safetensors" },
]
path = "models/controlnet"


[[sources]]
repo = "Shakker-Labs/FLUX.1-dev-ControlNet-Depth"
files = [
    { src = "diffusion_pytorch_model.safetensors", dest = "shakker_labs_flux_depth.safetensors" },
]
path = "models/controlnet"

[[sources]]
repo = "Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro"
files = [
    { src = "diffusion_pytorch_model.safetensors", dest = "shakker_labs_flux_union_pro.safetensors" },
]
path = "models/controlnet"

[[sources]]
repo = "Endless-Iterations/eltorverate"
files = [
    { src = "add_detail.safetensors", dest = "loras/add_detail.safetensors" },
    { src = "4x_NMKD-Superscale-SP178000_G.pth", dest = "upscale_models/4x_NMKD-Superscale-SP_178000_G.pth" },
]
path = "models"

[[sources]]
repo  ="camenduru/stable-diffusion-3.5-large"
files = ["sd3.5_large.safetensors"]
path  ="models/checkpoints"

